spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quizlet
    username: root
    password: mysql
server:
  port: 8080
logging:
  level:
    root: warn
    com:
      bfs:
        quizlet: debug
